# atsmarket-web-app/nginx.conf
server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Si el archivo no existe, sirve index.html (para Angular Router)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Impedir que se guarde en caché el Service Worker
    location = /service-worker.js {
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
    }

    # Impedir caché en el manifiesto
    location = /manifest.webmanifest {
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
    }

    # Opcional: comprime assets
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml;
}